### ISSUE TITLE
Need another fork to keep maintaining this

### ISSUE THREAD

**Issue by LordNoteworthy** [mozilla-services/pkcs7#73]
Hello,

[Greg](https://github.com/g-k) who was actively merging the PRs on this project can no longer operates on this repo because he moved away from Mozilla, please correct me if I am wrong.

Can someone suggest any alternative fork we can move to ? There are bunch of interesting PR that would be nice to get merged.

Cheers.

**Comment by cleverlzc** [comment]
+1

**Comment by hslatman** [comment]
We're maintaining [a branch in a fork](https://github.com/smallstep/pkcs7/pull/1). Some of the open PRs have already been pulled in, as well as other changes that are similar to some other open PRs. It's currently a branch, but we're close to merging that to our master. From there, we might rename the module and be a proper and maintained fork.

**Comment by hslatman** [comment]
Since my previous message we've moved from maintaining a branch to maintaining everything in `main`. The module was also renamed to `github.com/smallstep/pkcs7`. Should be a drop-in replacement for this this repo, just with more commits from existing PRs merged, as well as new additions. Check it out at https://github.com/smallstep/pkcs7 😄 

We'll release a tagged `v1` version soon. We'll move on to `v2` fairly soon after that, in which we'll change some default algorithms and potentially some other backwards incompatible changes.
