### ISSUE TITLE
Status of this repository?

### ISSUE THREAD

**Issue by hslatman** [mozilla-services/pkcs7#88]
Hi @hneiva, I noticed a new release and some recent commits to this repo. It was archived at the beginning of this year. Does this mean there'll be more activity here again? We've been maintaining a fork for a while at https://github.com/smallstep/pkcs7 now, and it would be good to know whether or not this repository intends to go forward.

**Comment by jmhodges** [comment]
No, so sorry, this team had to unarchive in order to solve some internal operational problems but don't currently have the bandwidth to support the community as well as y'all have. We're undergoing some renovations that mean we're not able do the backwards compat tests we'd like to use a different library (not because those libs aren't backwards compat, but because they fix, say, serialization bugs we're worried our current signatures would change under).  

I would recommend y'all continue with the fork!

**Comment by hslatman** [comment]
Thank you for your response, @jmhodges 🙂 

Sounds good; we'll continue with the fork.
